"""simple wms baseline

Revision ID: 50194f903b24
Revises:
Create Date: 2026-08-03 14:18:49.174693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50194f903b24'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=80), nullable=False),
    sa.Column('object_type', sa.String(length=80), nullable=False),
    sa.Column('object_uid', sa.String(length=120), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_events_created_at'), 'operation_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_operation_events_object_type'), 'operation_events', ['object_type'], unique=False)
    op.create_index(op.f('ix_operation_events_object_uid'), 'operation_events', ['object_uid'], unique=False)
    op.create_index(op.f('ix_operation_events_operation'), 'operation_events', ['operation'], unique=False)
    op.create_table('units_of_measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('dimension', sa.String(length=32), nullable=False),
    sa.Column('decimal_precision', sa.Integer(), nullable=False),
    sa.Column('factor_to_base', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('is_base', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('decimal_precision >= 0 AND decimal_precision <= 6', name='ck_uom_decimal_precision'),
    sa.CheckConstraint('factor_to_base > 0', name='ck_uom_factor_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_of_measure_code'), 'units_of_measure', ['code'], unique=True)
    op.create_index(op.f('ix_units_of_measure_dimension'), 'units_of_measure', ['dimension'], unique=False)
    op.create_index(op.f('ix_units_of_measure_is_base'), 'units_of_measure', ['is_base'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.Enum('PRODUCTION_OPERATOR', 'RECEIVING_CLERK', 'WAREHOUSE_CLERK', 'SHIPPING_OPERATOR', 'SENIOR_CLERK', 'WAREHOUSE_MANAGER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=True)
    op.create_table('equipment_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('device_kind', sa.String(length=32), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('connection_type', sa.String(length=32), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('queue_name', sa.String(length=120), nullable=True),
    sa.Column('serial_device', sa.String(length=160), nullable=True),
    sa.Column('driver_code', sa.String(length=80), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('port IS NULL OR (port >= 1 AND port <= 65535)', name='ck_equipment_port'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_profiles_code'), 'equipment_profiles', ['code'], unique=True)
    op.create_index(op.f('ix_equipment_profiles_connection_type'), 'equipment_profiles', ['connection_type'], unique=False)
    op.create_index(op.f('ix_equipment_profiles_device_kind'), 'equipment_profiles', ['device_kind'], unique=False)
    op.create_index(op.f('ix_equipment_profiles_is_default'), 'equipment_profiles', ['is_default'], unique=False)
    op.create_index(op.f('ix_equipment_profiles_warehouse_id'), 'equipment_profiles', ['warehouse_id'], unique=False)
    op.create_table('logistic_shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_uid', sa.String(length=40), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('destination', sa.String(length=160), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'RESERVED', 'EXPEDITION', 'LOADING', 'COMPLETED', 'CANCELLED', name='shipmentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logistic_shipments_shipment_uid'), 'logistic_shipments', ['shipment_uid'], unique=True)
    op.create_index(op.f('ix_logistic_shipments_status'), 'logistic_shipments', ['status'], unique=False)
    op.create_index(op.f('ix_logistic_shipments_warehouse_id'), 'logistic_shipments', ['warehouse_id'], unique=False)
    op.create_table('logistic_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_uid', sa.String(length=40), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.Enum('BUILD', 'PLACE', 'MOVE', 'SHIP', 'INVENTORY', 'TRANSFER', name='tasktype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus', native_enum=False, length=32), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='taskpriority', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('object_type', sa.String(length=40), nullable=False),
    sa.Column('object_uid', sa.String(length=120), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('assigned_to', sa.String(length=80), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logistic_tasks_assigned_to'), 'logistic_tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_logistic_tasks_created_at'), 'logistic_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_logistic_tasks_object_type'), 'logistic_tasks', ['object_type'], unique=False)
    op.create_index(op.f('ix_logistic_tasks_object_uid'), 'logistic_tasks', ['object_uid'], unique=False)
    op.create_index(op.f('ix_logistic_tasks_priority'), 'logistic_tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_logistic_tasks_status'), 'logistic_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_logistic_tasks_task_type'), 'logistic_tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_logistic_tasks_task_uid'), 'logistic_tasks', ['task_uid'], unique=True)
    op.create_index(op.f('ix_logistic_tasks_warehouse_id'), 'logistic_tasks', ['warehouse_id'], unique=False)
    op.create_table('logistic_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_uid', sa.String(length=40), nullable=False),
    sa.Column('source_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('destination_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('transfer_kind', sa.Enum('LOCAL', 'TRANSPORT', name='transferkind', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'RESERVED', 'EXPEDITION', 'LOADING', 'IN_TRANSIT', 'RECEIVING', 'COMPLETED', 'CANCELLED', name='transferstatus', native_enum=False, length=32), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('vehicle_number', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['source_warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logistic_transfers_destination_warehouse_id'), 'logistic_transfers', ['destination_warehouse_id'], unique=False)
    op.create_index(op.f('ix_logistic_transfers_source_warehouse_id'), 'logistic_transfers', ['source_warehouse_id'], unique=False)
    op.create_index(op.f('ix_logistic_transfers_status'), 'logistic_transfers', ['status'], unique=False)
    op.create_index(op.f('ix_logistic_transfers_transfer_kind'), 'logistic_transfers', ['transfer_kind'], unique=False)
    op.create_index(op.f('ix_logistic_transfers_transfer_uid'), 'logistic_transfers', ['transfer_uid'], unique=True)
    op.create_table('logistic_unit_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('identifier_prefix', sa.String(length=16), nullable=False),
    sa.Column('tare_weight', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('tare_weight_uom_id', sa.Integer(), nullable=True),
    sa.Column('max_weight', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('max_weight_uom_id', sa.Integer(), nullable=True),
    sa.Column('length_mm', sa.Integer(), nullable=True),
    sa.Column('width_mm', sa.Integer(), nullable=True),
    sa.Column('height_mm', sa.Integer(), nullable=True),
    sa.Column('can_contain_goods', sa.Boolean(), nullable=False),
    sa.Column('can_contain_units', sa.Boolean(), nullable=False),
    sa.Column('is_returnable', sa.Boolean(), nullable=False),
    sa.Column('barcode_template', sa.String(length=240), nullable=False),
    sa.Column('label_profile', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('height_mm IS NULL OR height_mm > 0', name='ck_logistic_type_height'),
    sa.CheckConstraint('length_mm IS NULL OR length_mm > 0', name='ck_logistic_type_length'),
    sa.CheckConstraint('max_weight IS NULL OR max_weight > 0', name='ck_logistic_type_max_weight'),
    sa.CheckConstraint('tare_weight IS NULL OR tare_weight >= 0', name='ck_logistic_type_tare_weight'),
    sa.CheckConstraint('width_mm IS NULL OR width_mm > 0', name='ck_logistic_type_width'),
    sa.ForeignKeyConstraint(['max_weight_uom_id'], ['units_of_measure.id'], ),
    sa.ForeignKeyConstraint(['tare_weight_uom_id'], ['units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logistic_unit_types_code'), 'logistic_unit_types', ['code'], unique=True)
    op.create_index(op.f('ix_logistic_unit_types_identifier_prefix'), 'logistic_unit_types', ['identifier_prefix'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('base_uom_id', sa.Integer(), nullable=True),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['base_uom_id'], ['units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_base_uom_id'), 'products', ['base_uom_id'], unique=False)
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=True)
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.Enum('RECEIVING', 'STORAGE', 'QUARANTINE', 'DISCREPANCY', 'EXPEDITION', 'TRANSFER_OUT', 'TRANSFER_IN', 'SCRAP', name='locationkind'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'code', name='uq_zone_warehouse_code')
    )
    op.create_index(op.f('ix_zones_code'), 'zones', ['code'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=80), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('quality_status', sa.String(length=40), nullable=False),
    sa.Column('operation_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'batch_number', name='uq_batch_product_number')
    )
    op.create_index(op.f('ix_batches_batch_number'), 'batches', ['batch_number'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('kind', sa.Enum('RECEIVING', 'STORAGE', 'QUARANTINE', 'DISCREPANCY', 'EXPEDITION', 'TRANSFER_OUT', 'TRANSFER_IN', 'SCRAP', name='locationkind'), nullable=False),
    sa.Column('capacity_units', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_code'), 'locations', ['code'], unique=True)
    op.create_table('logistic_unit_type_allowed_children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_type_id', sa.Integer(), nullable=False),
    sa.Column('child_type_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('parent_type_id <> child_type_id', name='ck_logistic_type_no_self_child'),
    sa.ForeignKeyConstraint(['child_type_id'], ['logistic_unit_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_type_id'], ['logistic_unit_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_type_id', 'child_type_id', name='uq_logistic_type_allowed_child')
    )
    op.create_index(op.f('ix_logistic_unit_type_allowed_children_child_type_id'), 'logistic_unit_type_allowed_children', ['child_type_id'], unique=False)
    op.create_index(op.f('ix_logistic_unit_type_allowed_children_parent_type_id'), 'logistic_unit_type_allowed_children', ['parent_type_id'], unique=False)
    op.create_table('logistic_inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_uid', sa.String(length=40), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=32), nullable=False),
    sa.Column('scope_parameters', sa.JSON(), nullable=False),
    sa.Column('current_location_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'COMPLETED', name='inventorystatus', native_enum=False, length=32), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['current_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logistic_inventories_inventory_uid'), 'logistic_inventories', ['inventory_uid'], unique=True)
    op.create_index(op.f('ix_logistic_inventories_scope_type'), 'logistic_inventories', ['scope_type'], unique=False)
    op.create_index(op.f('ix_logistic_inventories_status'), 'logistic_inventories', ['status'], unique=False)
    op.create_index(op.f('ix_logistic_inventories_warehouse_id'), 'logistic_inventories', ['warehouse_id'], unique=False)
    op.create_table('logistic_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'AVAILABLE', 'RESERVED', 'PICKING', 'EXPEDITION', 'LOADED', 'IN_TRANSIT', 'QUARANTINE', 'BLOCKED', 'DISASSEMBLED', 'WRITTEN_OFF', 'SHIPPED', name='logisticunitstatus'), nullable=False),
    sa.Column('parent_unit_id', sa.Integer(), nullable=True),
    sa.Column('current_location_id', sa.Integer(), nullable=True),
    sa.Column('measured_gross_weight', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('weight_uom_id', sa.Integer(), nullable=True),
    sa.Column('length_mm', sa.Integer(), nullable=True),
    sa.Column('width_mm', sa.Integer(), nullable=True),
    sa.Column('height_mm', sa.Integer(), nullable=True),
    sa.Column('status_before_hold', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('height_mm IS NULL OR height_mm > 0', name='ck_logistic_unit_height'),
    sa.CheckConstraint('length_mm IS NULL OR length_mm > 0', name='ck_logistic_unit_length'),
    sa.CheckConstraint('measured_gross_weight IS NULL OR measured_gross_weight > 0', name='ck_logistic_unit_gross_weight'),
    sa.CheckConstraint('parent_unit_id IS NULL OR parent_unit_id <> id', name='ck_logistic_unit_no_self_parent'),
    sa.CheckConstraint('width_mm IS NULL OR width_mm > 0', name='ck_logistic_unit_width'),
    sa.ForeignKeyConstraint(['current_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['parent_unit_id'], ['logistic_units.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['logistic_unit_types.id'], ),
    sa.ForeignKeyConstraint(['weight_uom_id'], ['units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logistic_units_current_location_id'), 'logistic_units', ['current_location_id'], unique=False)
    op.create_index(op.f('ix_logistic_units_parent_unit_id'), 'logistic_units', ['parent_unit_id'], unique=False)
    op.create_index(op.f('ix_logistic_units_status'), 'logistic_units', ['status'], unique=False)
    op.create_index(op.f('ix_logistic_units_type_id'), 'logistic_units', ['type_id'], unique=False)
    op.create_index(op.f('ix_logistic_units_uid'), 'logistic_units', ['uid'], unique=True)
    op.create_table('warehouse_map_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.String(length=32), nullable=False),
    sa.Column('item_key', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('rotation', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['warehouse_map_items.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', name='uq_warehouse_map_location'),
    sa.UniqueConstraint('warehouse_id', 'item_key', name='uq_warehouse_map_item_key')
    )
    op.create_index(op.f('ix_warehouse_map_items_item_type'), 'warehouse_map_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_warehouse_map_items_parent_id'), 'warehouse_map_items', ['parent_id'], unique=False)
    op.create_index(op.f('ix_warehouse_map_items_warehouse_id'), 'warehouse_map_items', ['warehouse_id'], unique=False)
    op.create_table('logistic_inventory_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('logistic_unit_id', sa.Integer(), nullable=False),
    sa.Column('expected_location_id', sa.Integer(), nullable=True),
    sa.Column('actual_location_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('EXPECTED', 'SCANNED', 'MISSING', 'EXTRA', 'WRONG_LOCATION', name='inventorylinestatus', native_enum=False, length=32), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_action', sa.String(length=40), nullable=True),
    sa.Column('resolution_actor', sa.String(length=80), nullable=True),
    sa.Column('resolution_reason', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actual_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['expected_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['logistic_inventories.id'], ),
    sa.ForeignKeyConstraint(['logistic_unit_id'], ['logistic_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_id', 'logistic_unit_id', name='uq_logistic_inventory_unit')
    )
    op.create_index(op.f('ix_logistic_inventory_lines_actual_location_id'), 'logistic_inventory_lines', ['actual_location_id'], unique=False)
    op.create_index(op.f('ix_logistic_inventory_lines_expected_location_id'), 'logistic_inventory_lines', ['expected_location_id'], unique=False)
    op.create_index(op.f('ix_logistic_inventory_lines_inventory_id'), 'logistic_inventory_lines', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_logistic_inventory_lines_logistic_unit_id'), 'logistic_inventory_lines', ['logistic_unit_id'], unique=False)
    op.create_index(op.f('ix_logistic_inventory_lines_status'), 'logistic_inventory_lines', ['status'], unique=False)
    op.create_table('logistic_inventory_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('expected_unit_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UNCHECKED', 'CHECKED', 'PROBLEM', name='inventorylocationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_by', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['logistic_inventories.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_id', 'location_id', name='uq_logistic_inventory_location')
    )
    op.create_index(op.f('ix_logistic_inventory_locations_inventory_id'), 'logistic_inventory_locations', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_logistic_inventory_locations_location_id'), 'logistic_inventory_locations', ['location_id'], unique=False)
    op.create_index(op.f('ix_logistic_inventory_locations_status'), 'logistic_inventory_locations', ['status'], unique=False)
    op.create_table('logistic_shipment_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('logistic_unit_id', sa.Integer(), nullable=False),
    sa.Column('source_location_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('moved_to_expedition_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['logistic_unit_id'], ['logistic_units.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['logistic_shipments.id'], ),
    sa.ForeignKeyConstraint(['source_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id', 'logistic_unit_id', name='uq_logistic_shipment_unit')
    )
    op.create_index(op.f('ix_logistic_shipment_units_logistic_unit_id'), 'logistic_shipment_units', ['logistic_unit_id'], unique=False)
    op.create_index(op.f('ix_logistic_shipment_units_shipment_id'), 'logistic_shipment_units', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_logistic_shipment_units_status'), 'logistic_shipment_units', ['status'], unique=False)
    op.create_table('logistic_transfer_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('logistic_unit_id', sa.Integer(), nullable=False),
    sa.Column('source_location_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('moved_to_expedition_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['logistic_unit_id'], ['logistic_units.id'], ),
    sa.ForeignKeyConstraint(['source_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['logistic_transfers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_id', 'logistic_unit_id', name='uq_logistic_transfer_unit')
    )
    op.create_index(op.f('ix_logistic_transfer_units_logistic_unit_id'), 'logistic_transfer_units', ['logistic_unit_id'], unique=False)
    op.create_index(op.f('ix_logistic_transfer_units_status'), 'logistic_transfer_units', ['status'], unique=False)
    op.create_index(op.f('ix_logistic_transfer_units_transfer_id'), 'logistic_transfer_units', ['transfer_id'], unique=False)
    op.create_table('logistic_unit_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logistic_unit_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('uom_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_logistic_unit_content_quantity'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['logistic_unit_id'], ['logistic_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['uom_id'], ['units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logistic_unit_id', 'product_id', 'batch_id', 'uom_id', name='uq_logistic_unit_content_line')
    )
    op.create_index(op.f('ix_logistic_unit_contents_batch_id'), 'logistic_unit_contents', ['batch_id'], unique=False)
    op.create_index(op.f('ix_logistic_unit_contents_logistic_unit_id'), 'logistic_unit_contents', ['logistic_unit_id'], unique=False)
    op.create_index(op.f('ix_logistic_unit_contents_product_id'), 'logistic_unit_contents', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logistic_unit_contents_product_id'), table_name='logistic_unit_contents')
    op.drop_index(op.f('ix_logistic_unit_contents_logistic_unit_id'), table_name='logistic_unit_contents')
    op.drop_index(op.f('ix_logistic_unit_contents_batch_id'), table_name='logistic_unit_contents')
    op.drop_table('logistic_unit_contents')
    op.drop_index(op.f('ix_logistic_transfer_units_transfer_id'), table_name='logistic_transfer_units')
    op.drop_index(op.f('ix_logistic_transfer_units_status'), table_name='logistic_transfer_units')
    op.drop_index(op.f('ix_logistic_transfer_units_logistic_unit_id'), table_name='logistic_transfer_units')
    op.drop_table('logistic_transfer_units')
    op.drop_index(op.f('ix_logistic_shipment_units_status'), table_name='logistic_shipment_units')
    op.drop_index(op.f('ix_logistic_shipment_units_shipment_id'), table_name='logistic_shipment_units')
    op.drop_index(op.f('ix_logistic_shipment_units_logistic_unit_id'), table_name='logistic_shipment_units')
    op.drop_table('logistic_shipment_units')
    op.drop_index(op.f('ix_logistic_inventory_locations_status'), table_name='logistic_inventory_locations')
    op.drop_index(op.f('ix_logistic_inventory_locations_location_id'), table_name='logistic_inventory_locations')
    op.drop_index(op.f('ix_logistic_inventory_locations_inventory_id'), table_name='logistic_inventory_locations')
    op.drop_table('logistic_inventory_locations')
    op.drop_index(op.f('ix_logistic_inventory_lines_status'), table_name='logistic_inventory_lines')
    op.drop_index(op.f('ix_logistic_inventory_lines_logistic_unit_id'), table_name='logistic_inventory_lines')
    op.drop_index(op.f('ix_logistic_inventory_lines_inventory_id'), table_name='logistic_inventory_lines')
    op.drop_index(op.f('ix_logistic_inventory_lines_expected_location_id'), table_name='logistic_inventory_lines')
    op.drop_index(op.f('ix_logistic_inventory_lines_actual_location_id'), table_name='logistic_inventory_lines')
    op.drop_table('logistic_inventory_lines')
    op.drop_index(op.f('ix_warehouse_map_items_warehouse_id'), table_name='warehouse_map_items')
    op.drop_index(op.f('ix_warehouse_map_items_parent_id'), table_name='warehouse_map_items')
    op.drop_index(op.f('ix_warehouse_map_items_item_type'), table_name='warehouse_map_items')
    op.drop_table('warehouse_map_items')
    op.drop_index(op.f('ix_logistic_units_uid'), table_name='logistic_units')
    op.drop_index(op.f('ix_logistic_units_type_id'), table_name='logistic_units')
    op.drop_index(op.f('ix_logistic_units_status'), table_name='logistic_units')
    op.drop_index(op.f('ix_logistic_units_parent_unit_id'), table_name='logistic_units')
    op.drop_index(op.f('ix_logistic_units_current_location_id'), table_name='logistic_units')
    op.drop_table('logistic_units')
    op.drop_index(op.f('ix_logistic_inventories_warehouse_id'), table_name='logistic_inventories')
    op.drop_index(op.f('ix_logistic_inventories_status'), table_name='logistic_inventories')
    op.drop_index(op.f('ix_logistic_inventories_scope_type'), table_name='logistic_inventories')
    op.drop_index(op.f('ix_logistic_inventories_inventory_uid'), table_name='logistic_inventories')
    op.drop_table('logistic_inventories')
    op.drop_index(op.f('ix_logistic_unit_type_allowed_children_parent_type_id'), table_name='logistic_unit_type_allowed_children')
    op.drop_index(op.f('ix_logistic_unit_type_allowed_children_child_type_id'), table_name='logistic_unit_type_allowed_children')
    op.drop_table('logistic_unit_type_allowed_children')
    op.drop_index(op.f('ix_locations_code'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_batches_batch_number'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_zones_code'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_index(op.f('ix_products_base_uom_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_logistic_unit_types_identifier_prefix'), table_name='logistic_unit_types')
    op.drop_index(op.f('ix_logistic_unit_types_code'), table_name='logistic_unit_types')
    op.drop_table('logistic_unit_types')
    op.drop_index(op.f('ix_logistic_transfers_transfer_uid'), table_name='logistic_transfers')
    op.drop_index(op.f('ix_logistic_transfers_transfer_kind'), table_name='logistic_transfers')
    op.drop_index(op.f('ix_logistic_transfers_status'), table_name='logistic_transfers')
    op.drop_index(op.f('ix_logistic_transfers_source_warehouse_id'), table_name='logistic_transfers')
    op.drop_index(op.f('ix_logistic_transfers_destination_warehouse_id'), table_name='logistic_transfers')
    op.drop_table('logistic_transfers')
    op.drop_index(op.f('ix_logistic_tasks_warehouse_id'), table_name='logistic_tasks')
    op.drop_index(op.f('ix_logistic_tasks_task_uid'), table_name='logistic_tasks')
    op.drop_index(op.f('ix_logistic_tasks_task_type'), table_name='logistic_tasks')
    op.drop_index(op.f('ix_logistic_tasks_status'), table_name='logistic_tasks')
    op.drop_index(op.f('ix_logistic_tasks_priority'), table_name='logistic_tasks')
    op.drop_index(op.f('ix_logistic_tasks_object_uid'), table_name='logistic_tasks')
    op.drop_index(op.f('ix_logistic_tasks_object_type'), table_name='logistic_tasks')
    op.drop_index(op.f('ix_logistic_tasks_created_at'), table_name='logistic_tasks')
    op.drop_index(op.f('ix_logistic_tasks_assigned_to'), table_name='logistic_tasks')
    op.drop_table('logistic_tasks')
    op.drop_index(op.f('ix_logistic_shipments_warehouse_id'), table_name='logistic_shipments')
    op.drop_index(op.f('ix_logistic_shipments_status'), table_name='logistic_shipments')
    op.drop_index(op.f('ix_logistic_shipments_shipment_uid'), table_name='logistic_shipments')
    op.drop_table('logistic_shipments')
    op.drop_index(op.f('ix_equipment_profiles_warehouse_id'), table_name='equipment_profiles')
    op.drop_index(op.f('ix_equipment_profiles_is_default'), table_name='equipment_profiles')
    op.drop_index(op.f('ix_equipment_profiles_device_kind'), table_name='equipment_profiles')
    op.drop_index(op.f('ix_equipment_profiles_connection_type'), table_name='equipment_profiles')
    op.drop_index(op.f('ix_equipment_profiles_code'), table_name='equipment_profiles')
    op.drop_table('equipment_profiles')
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_units_of_measure_is_base'), table_name='units_of_measure')
    op.drop_index(op.f('ix_units_of_measure_dimension'), table_name='units_of_measure')
    op.drop_index(op.f('ix_units_of_measure_code'), table_name='units_of_measure')
    op.drop_table('units_of_measure')
    op.drop_index(op.f('ix_operation_events_operation'), table_name='operation_events')
    op.drop_index(op.f('ix_operation_events_object_uid'), table_name='operation_events')
    op.drop_index(op.f('ix_operation_events_object_type'), table_name='operation_events')
    op.drop_index(op.f('ix_operation_events_created_at'), table_name='operation_events')
    op.drop_table('operation_events')
    # ### end Alembic commands ###
