"""add warehouse address hierarchy

Revision ID: 6c0037a4f16a
Revises: 50194f903b24
Create Date: 2026-08-03 14:42:45.861183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c0037a4f16a'
down_revision: Union[str, Sequence[str], None] = '50194f903b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aisles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'code', name='uq_aisle_zone_code')
    )
    op.create_index(op.f('ix_aisles_code'), 'aisles', ['code'], unique=False)
    op.create_index(op.f('ix_aisles_zone_id'), 'aisles', ['zone_id'], unique=False)
    op.create_table('racks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aisle_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aisle_id'], ['aisles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aisle_id', 'code', name='uq_rack_aisle_code')
    )
    op.create_index(op.f('ix_racks_aisle_id'), 'racks', ['aisle_id'], unique=False)
    op.create_index(op.f('ix_racks_code'), 'racks', ['code'], unique=False)
    op.create_table('rack_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rack_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rack_id', 'code', name='uq_rack_section_code')
    )
    op.create_index(op.f('ix_rack_sections_code'), 'rack_sections', ['code'], unique=False)
    op.create_index(op.f('ix_rack_sections_rack_id'), 'rack_sections', ['rack_id'], unique=False)
    op.create_table('rack_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('elevation_mm', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('elevation_mm IS NULL OR elevation_mm >= 0', name='ck_rack_level_elevation'),
    sa.ForeignKeyConstraint(['section_id'], ['rack_sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'code', name='uq_rack_level_code')
    )
    op.create_index(op.f('ix_rack_levels_code'), 'rack_levels', ['code'], unique=False)
    op.create_index(op.f('ix_rack_levels_section_id'), 'rack_levels', ['section_id'], unique=False)
    with op.batch_alter_table('locations') as batch_op:
        batch_op.add_column(sa.Column('aisle_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rack_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('level_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('position_code', sa.String(length=32), nullable=True))
        batch_op.create_index(op.f('ix_locations_aisle_id'), ['aisle_id'], unique=False)
        batch_op.create_index(op.f('ix_locations_level_id'), ['level_id'], unique=False)
        batch_op.create_index(op.f('ix_locations_rack_id'), ['rack_id'], unique=False)
        batch_op.create_index(op.f('ix_locations_section_id'), ['section_id'], unique=False)
        batch_op.create_unique_constraint('uq_location_level_position', ['level_id', 'position_code'])
        batch_op.create_check_constraint(
            'ck_location_complete_address',
            '(aisle_id IS NULL AND rack_id IS NULL AND section_id IS NULL '
            'AND level_id IS NULL AND position_code IS NULL) OR '
            '(aisle_id IS NOT NULL AND rack_id IS NOT NULL AND section_id IS NOT NULL '
            'AND level_id IS NOT NULL AND position_code IS NOT NULL)',
        )
        batch_op.create_foreign_key('fk_locations_aisle_id', 'aisles', ['aisle_id'], ['id'])
        batch_op.create_foreign_key('fk_locations_rack_id', 'racks', ['rack_id'], ['id'])
        batch_op.create_foreign_key('fk_locations_section_id', 'rack_sections', ['section_id'], ['id'])
        batch_op.create_foreign_key('fk_locations_level_id', 'rack_levels', ['level_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations') as batch_op:
        batch_op.drop_constraint('fk_locations_level_id', type_='foreignkey')
        batch_op.drop_constraint('fk_locations_section_id', type_='foreignkey')
        batch_op.drop_constraint('fk_locations_rack_id', type_='foreignkey')
        batch_op.drop_constraint('fk_locations_aisle_id', type_='foreignkey')
        batch_op.drop_constraint('ck_location_complete_address', type_='check')
        batch_op.drop_constraint('uq_location_level_position', type_='unique')
        batch_op.drop_index(op.f('ix_locations_section_id'))
        batch_op.drop_index(op.f('ix_locations_rack_id'))
        batch_op.drop_index(op.f('ix_locations_level_id'))
        batch_op.drop_index(op.f('ix_locations_aisle_id'))
        batch_op.drop_column('position_code')
        batch_op.drop_column('level_id')
        batch_op.drop_column('section_id')
        batch_op.drop_column('rack_id')
        batch_op.drop_column('aisle_id')
    op.drop_index(op.f('ix_rack_levels_section_id'), table_name='rack_levels')
    op.drop_index(op.f('ix_rack_levels_code'), table_name='rack_levels')
    op.drop_table('rack_levels')
    op.drop_index(op.f('ix_rack_sections_rack_id'), table_name='rack_sections')
    op.drop_index(op.f('ix_rack_sections_code'), table_name='rack_sections')
    op.drop_table('rack_sections')
    op.drop_index(op.f('ix_racks_code'), table_name='racks')
    op.drop_index(op.f('ix_racks_aisle_id'), table_name='racks')
    op.drop_table('racks')
    op.drop_index(op.f('ix_aisles_zone_id'), table_name='aisles')
    op.drop_index(op.f('ix_aisles_code'), table_name='aisles')
    op.drop_table('aisles')
    # ### end Alembic commands ###
