"""baseline schema

Revision ID: a2efa5d8a2f4
Revises:
Create Date: 2026-07-22 19:24:48.850593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2efa5d8a2f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=80), nullable=False),
    sa.Column('object_type', sa.String(length=80), nullable=False),
    sa.Column('object_uid', sa.String(length=120), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_events_created_at'), 'operation_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_operation_events_object_type'), 'operation_events', ['object_type'], unique=False)
    op.create_index(op.f('ix_operation_events_object_uid'), 'operation_events', ['object_uid'], unique=False)
    op.create_index(op.f('ix_operation_events_operation'), 'operation_events', ['operation'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('quantity_per_box', sa.Integer(), nullable=False),
    sa.Column('boxes_per_pallet', sa.Integer(), nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=True)
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_uid', sa.String(length=40), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('destination', sa.String(length=160), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'RESERVED', 'EXPEDITION', 'LOADING', 'COMPLETED', 'CANCELLED', name='shipmentstatus'), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_shipment_uid'), 'shipments', ['shipment_uid'], unique=True)
    op.create_index(op.f('ix_shipments_status'), 'shipments', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.Enum('PRODUCTION_OPERATOR', 'RECEIVING_CLERK', 'WAREHOUSE_CLERK', 'SHIPPING_OPERATOR', 'SENIOR_CLERK', 'WAREHOUSE_MANAGER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=True)
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=80), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('quality_status', sa.String(length=40), nullable=False),
    sa.Column('operation_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'batch_number', name='uq_batch_product_number')
    )
    op.create_index(op.f('ix_batches_batch_number'), 'batches', ['batch_number'], unique=False)
    op.create_table('warehouse_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_uid', sa.String(length=40), nullable=False),
    sa.Column('source_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('destination_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'RESERVED', 'EXPEDITION', 'LOADING', 'IN_TRANSIT', 'RECEIVING', 'COMPLETED', 'CANCELLED', name='transferstatus'), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('vehicle_number', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['source_warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_transfers_destination_warehouse_id'), 'warehouse_transfers', ['destination_warehouse_id'], unique=False)
    op.create_index(op.f('ix_warehouse_transfers_source_warehouse_id'), 'warehouse_transfers', ['source_warehouse_id'], unique=False)
    op.create_index(op.f('ix_warehouse_transfers_status'), 'warehouse_transfers', ['status'], unique=False)
    op.create_index(op.f('ix_warehouse_transfers_transfer_uid'), 'warehouse_transfers', ['transfer_uid'], unique=True)
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.Enum('RECEIVING', 'STORAGE', 'QUARANTINE', 'DISCREPANCY', 'EXPEDITION', 'TRANSFER_OUT', 'TRANSFER_IN', 'SCRAP', name='locationkind'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'code', name='uq_zone_warehouse_code')
    )
    op.create_index(op.f('ix_zones_code'), 'zones', ['code'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('kind', sa.Enum('RECEIVING', 'STORAGE', 'QUARANTINE', 'DISCREPANCY', 'EXPEDITION', 'TRANSFER_OUT', 'TRANSFER_IN', 'SCRAP', name='locationkind'), nullable=False),
    sa.Column('capacity_pallets', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_code'), 'locations', ['code'], unique=True)
    op.create_table('inventory_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_uid', sa.String(length=40), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('current_location_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'COMPLETED', name='inventorystatus'), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['current_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_sessions_inventory_uid'), 'inventory_sessions', ['inventory_uid'], unique=True)
    op.create_index(op.f('ix_inventory_sessions_status'), 'inventory_sessions', ['status'], unique=False)
    op.create_table('pallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pallet_uid', sa.String(length=40), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'WAITING_PLACEMENT', 'AVAILABLE', 'RESERVED', 'PICKING', 'EXPEDITION', 'LOADED', 'IN_TRANSIT', 'QUARANTINE', 'BLOCKED', 'DISASSEMBLED', 'WRITTEN_OFF', 'SHIPPED', name='palletstatus'), nullable=False),
    sa.Column('current_location_id', sa.Integer(), nullable=True),
    sa.Column('is_mixed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['current_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pallets_pallet_uid'), 'pallets', ['pallet_uid'], unique=True)
    op.create_index(op.f('ix_pallets_status'), 'pallets', ['status'], unique=False)
    op.create_table('warehouse_map_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.String(length=32), nullable=False),
    sa.Column('item_key', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('rotation', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['warehouse_map_items.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', name='uq_warehouse_map_location'),
    sa.UniqueConstraint('warehouse_id', 'item_key', name='uq_warehouse_map_item_key')
    )
    op.create_index(op.f('ix_warehouse_map_items_item_type'), 'warehouse_map_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_warehouse_map_items_parent_id'), 'warehouse_map_items', ['parent_id'], unique=False)
    op.create_index(op.f('ix_warehouse_map_items_warehouse_id'), 'warehouse_map_items', ['warehouse_id'], unique=False)
    op.create_table('boxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('box_uid', sa.String(length=40), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('LABEL_CREATED', 'ACCEPTED_FROM_PRODUCTION', 'IN_OPEN_PALLET', 'IN_CLOSED_PALLET', 'BLOCKED', 'QUARANTINE', 'DAMAGED', 'WRITTEN_OFF', 'SHIPPED', name='boxstatus'), nullable=False),
    sa.Column('current_pallet_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['current_pallet_id'], ['pallets.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boxes_box_uid'), 'boxes', ['box_uid'], unique=True)
    op.create_index(op.f('ix_boxes_status'), 'boxes', ['status'], unique=False)
    op.create_table('inventory_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('pallet_id', sa.Integer(), nullable=False),
    sa.Column('expected_location_id', sa.Integer(), nullable=True),
    sa.Column('actual_location_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('EXPECTED', 'SCANNED', 'MISSING', 'EXTRA', 'WRONG_LOCATION', name='inventorylinestatus'), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actual_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['expected_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory_sessions.id'], ),
    sa.ForeignKeyConstraint(['pallet_id'], ['pallets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_id', 'pallet_id', name='uq_inventory_pallet')
    )
    op.create_index(op.f('ix_inventory_lines_status'), 'inventory_lines', ['status'], unique=False)
    op.create_table('shipment_pallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('pallet_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('moved_to_expedition_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pallet_id'], ['pallets.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pallet_id', name='uq_active_shipment_pallet'),
    sa.UniqueConstraint('shipment_id', 'pallet_id', name='uq_shipment_pallet')
    )
    op.create_index(op.f('ix_shipment_pallets_status'), 'shipment_pallets', ['status'], unique=False)
    op.create_table('warehouse_transfer_pallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('pallet_id', sa.Integer(), nullable=False),
    sa.Column('source_location_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('moved_to_expedition_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pallet_id'], ['pallets.id'], ),
    sa.ForeignKeyConstraint(['source_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['warehouse_transfers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_id', 'pallet_id', name='uq_transfer_pallet')
    )
    op.create_index(op.f('ix_warehouse_transfer_pallets_pallet_id'), 'warehouse_transfer_pallets', ['pallet_id'], unique=False)
    op.create_index(op.f('ix_warehouse_transfer_pallets_status'), 'warehouse_transfer_pallets', ['status'], unique=False)
    op.create_index(op.f('ix_warehouse_transfer_pallets_transfer_id'), 'warehouse_transfer_pallets', ['transfer_id'], unique=False)
    op.create_table('pallet_boxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pallet_id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['box_id'], ['boxes.id'], ),
    sa.ForeignKeyConstraint(['pallet_id'], ['pallets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('box_id', name='uq_pallet_box_current_box')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pallet_boxes')
    op.drop_index(op.f('ix_warehouse_transfer_pallets_transfer_id'), table_name='warehouse_transfer_pallets')
    op.drop_index(op.f('ix_warehouse_transfer_pallets_status'), table_name='warehouse_transfer_pallets')
    op.drop_index(op.f('ix_warehouse_transfer_pallets_pallet_id'), table_name='warehouse_transfer_pallets')
    op.drop_table('warehouse_transfer_pallets')
    op.drop_index(op.f('ix_shipment_pallets_status'), table_name='shipment_pallets')
    op.drop_table('shipment_pallets')
    op.drop_index(op.f('ix_inventory_lines_status'), table_name='inventory_lines')
    op.drop_table('inventory_lines')
    op.drop_index(op.f('ix_boxes_status'), table_name='boxes')
    op.drop_index(op.f('ix_boxes_box_uid'), table_name='boxes')
    op.drop_table('boxes')
    op.drop_index(op.f('ix_warehouse_map_items_warehouse_id'), table_name='warehouse_map_items')
    op.drop_index(op.f('ix_warehouse_map_items_parent_id'), table_name='warehouse_map_items')
    op.drop_index(op.f('ix_warehouse_map_items_item_type'), table_name='warehouse_map_items')
    op.drop_table('warehouse_map_items')
    op.drop_index(op.f('ix_pallets_status'), table_name='pallets')
    op.drop_index(op.f('ix_pallets_pallet_uid'), table_name='pallets')
    op.drop_table('pallets')
    op.drop_index(op.f('ix_inventory_sessions_status'), table_name='inventory_sessions')
    op.drop_index(op.f('ix_inventory_sessions_inventory_uid'), table_name='inventory_sessions')
    op.drop_table('inventory_sessions')
    op.drop_index(op.f('ix_locations_code'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_zones_code'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_warehouse_transfers_transfer_uid'), table_name='warehouse_transfers')
    op.drop_index(op.f('ix_warehouse_transfers_status'), table_name='warehouse_transfers')
    op.drop_index(op.f('ix_warehouse_transfers_source_warehouse_id'), table_name='warehouse_transfers')
    op.drop_index(op.f('ix_warehouse_transfers_destination_warehouse_id'), table_name='warehouse_transfers')
    op.drop_table('warehouse_transfers')
    op.drop_index(op.f('ix_batches_batch_number'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shipments_status'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_shipment_uid'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_operation_events_operation'), table_name='operation_events')
    op.drop_index(op.f('ix_operation_events_object_uid'), table_name='operation_events')
    op.drop_index(op.f('ix_operation_events_object_type'), table_name='operation_events')
    op.drop_index(op.f('ix_operation_events_created_at'), table_name='operation_events')
    op.drop_table('operation_events')
    # ### end Alembic commands ###
