CODE_SEPARATOR = "-"

BOX_CODE_PREFIX = "BOX"
PALLET_CODE_PREFIX = "PLT"
SHIPMENT_CODE_PREFIX = "SHP"
INVENTORY_CODE_PREFIX = "INV"
TRANSFER_CODE_PREFIX = "TRF"
TASK_CODE_PREFIX = "TSK"

DEFAULT_WAREHOUSE_CODE = "WH01"
DEFAULT_WAREHOUSE_NAME = "Основной склад 1"
DEFAULT_CITY = "Москва"
DEFAULT_UNIT = "шт"

STORAGE_ZONE_CODE = "FR01"
STORAGE_ZONE_NAME = "Морозильное хранение"
RECEIVING_ZONE_CODE = "RCV"
RECEIVING_ZONE_NAME = "Зона приемки"
TRANSFER_IN_ZONE_CODE = "TRIN"
TRANSFER_IN_ZONE_NAME = "Зона межскладской приемки"

RECEIVING_LOCATION_SUFFIX = "P01"
TRANSFER_IN_LOCATION_SUFFIX = "STAGE"
STORAGE_LOCATION_PATTERN = "R01-B01-L01-P{index:02d}"
